services:
    app:
        build:
            context: .
            dockerfile: docker/prod/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        ports:
            - "8080:80"
        environment:
            APP_ENV: production
            APP_KEY: ${APP_KEY}
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_CLIENT: phpredis
            REDIS_PORT: 6379
            CACHE_STORE: redis
            SESSION_DRIVER: redis
            QUEUE_CONNECTION: redis
        depends_on:
            - db
            - redis
        networks:
            - laravel
            - nginx-network
    db:
        image: postgres:16
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel
    redis:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
    nginx-network:
        external: true
